fablab-chaux-de-fonds/Interlab

README.md

Change name of project

---

frontend/package-lock.json
frontend/src/scripts/index.js
frontend/src/scripts/vue.js
frontend/src/styles/custom.scss
frontend/webpack/webpack.common.js
frontend/webpack/webpack.config.dev.js
frontend/webpack/webpack.config.prod.js
interlab/templates/vuejs.html

Page loading display first "raw" html before style loading (1-2 sec)
Changed :
* Re-enable CSS from html header instead of injected from javascript
* Split bundle from VueJS specific pages from main App bundle

Dev loading issues

---

accounts/backends.py
accounts/templates/accounts/nav.html
accounts/templates/accounts/profile.html
accounts/templates/accounts/user-edit.html
accounts/templates/accounts/user-summary.html
accounts/templates/organizations/email/invitation_body.html
accounts/templates/organizations/register_form.html
accounts/templates/registration/password_change_form.html
accounts/templates/registration/password_reset_form.html
accounts/views.py
env.example
frontend/src/styles/buttons.scss
frontend/src/styles/forms.scss
interlab/settings.py
interlab/templates/base.html
interlab/templates/navbar-header.html
locale/fr/LC_MESSAGES/django.po
newsletter/templates/forms/newsletter.html

Ready for released https://github.com/fablab-chaux-de-fonds/Interlab/issues/20 https://github.com/fablab-chaux-de-fonds/Interlab/issues/21 https://github.com/fablab-chaux-de-fonds/Interlab/issues/22 https://github.com/fablab-chaux-de-fonds/Interlab/issues/23 https://github.com/fablab-chaux-de-fonds/Interlab/issues/24 https://github.com/fablab-chaux-de-fonds/Interlab/issues/50 https://github.com/fablab-chaux-de-fonds/Interlab/issues/51 https://github.com/fablab-chaux-de-fonds/Interlab/issues/102

Usability testing

---

README.md
interlab/settings.py
requirements.txt
tools/fabmanager-import.py

* Ability to support bcrypt password (for fabmanager compatibility)
* Update importation script to include profiles, trainings and subscriptions

Dev tool import

---

fabcal/views.py
frontend/src/styles/alerts.scss

* fix color of border for danger/warning message

Issue #170

---

accounts/forms.py
accounts/views.py

* Email was sent every time the user was edited by super user
* Improve confirmation messages (dates modification vs changing subscription type)
Indirectly linked to #173

Improve management of subscription updates, reduce number of mails

---

fabcal/templates/fabcal/opening_calendar.html

Remove in code and add informations in django CMS

---

fabcal/templates/fabcal/training_registration_form.html

Fix issue #225

---

interlab/templates/navbar-header.html

Fix issue #228

---

machines/filters.py

250-filtre-machine-faire-des-filtre-avec-des-and

---

interlab/settings.py
requirements.txt

* add [django-db-logger](https://github.com/CiCiUi/django-db-logger)
* Catch error 500 and save in db
Need to migrate to apply modifications

263 implement logging

---

newsletter/templates/forms/newsletter.html

FIX #171, force absolute URL for subpaths

Force newsletter path to be absolute

---

fabcal/forms.py
locale/fr/LC_MESSAGES/django.po
requirements.txt

* add [Babel](https://babel.pocoo.org/en/latest/) package to format datetime in local language.
close #253

253-message-après-réservation-machine-la-date-en-anglais-traduire

---

fabcal/templates/fabcal/fablab.ics

Fix for mobile import

---

fabcal/cms_plugins.py
frontend/src/components/OpeningCalendar.vue

308-ui-reduire-la-taille-de-badge-machine

---

frontend/src/styles/icons.scss
machines/templates/trainings/waiting_list.html

197-liste-dattente-formation

---

accounts/templates/accounts/email/subscription_updated.html
locale/fr/LC_MESSAGES/django.po
payments/views.py

This reverts commit 35dc7bb77d591482875c992138443cd6de0167bc.

Revert "Fix #420 (#424)"

---

payments/views.py

FIX: Direct button require create session in GET method too

---

payments/views.py

Resolve #434, get default access on category change

---

machines/templates/trainings/show_next_trainings.html

453-sinscrire-liste-formation-ne-fonctionne-pas

---

fabcal/templates/fabcal/email/machine_reservation_confirmation.html
locale/fr/LC_MESSAGES/django.po

Quick fix. 
Link should be get from context_data (#463)

458-mail-de-confirmation-de-réservation-ajouter-annulation-jusquà-24h-avant-le-début-de-la-réservation-1

---

accounts/forms.py
accounts/validators.py
locale/fr/LC_MESSAGES/django.po
requirements.txt

321-gestion-de-lerreur-si-addresse-mail-pas-valable-durant-linscription

---

machines/views.py

462-inverser-lordre-chrnologique

---

accounts/templates/accounts/profile.html

459-petit-crayon-pour-modifier-au-lieu-flèche-dans-le-profil

---

accounts/templates/accounts/profile.html
locale/fr/LC_MESSAGES/django.po

452 message erreur suppression reservation dans 24h

---

fabcal/templates/fabcal/machine/reservation_form.html
frontend/src/styles/forms.scss
interlab/templates/forms/base_forms.html
machines/admin.py
machines/templates/machines/price.html
machines/templates/machines/show.html

Improve pricing display

---

fabcal/forms.py
locale/fr/LC_MESSAGES/django.po

495-mail-validation-formation-ajouter-le-nom-de-la-machine-dans-le-sujet

---

locale/fr/LC_MESSAGES/django.po
machines/templates/trainings/info.html
machines/templates/trainings/show_next_trainings.html

445-ajouter-que-le-bon-machine-des-formations-est-valable-2-mois

---

accounts/forms.py
locale/fr/LC_MESSAGES/django.po

324-traduction-message-update-user-from-superuser

---

accounts/templates/accounts/profile.html

438-mise-à-jour-de-lavatar-en-fonction-de-la-réservation

---

frontend/src/components/OpeningCalendar.vue

466-problème-daffichage-des-heures-sur-ipad

---

share/templates/share/post_list.html
share/templates/share/post_list_items.html

449-ui-sur-la-page-quest-ce-quon-y-fabrique

---

accounts/templates/accounts/profile.html

510-réseration-list-sur-mobile

---

fabcal/templates/fabcal/event_info.html
locale/fr/LC_MESSAGES/django.po
machines/templates/machines/show.html
machines/templates/trainings/show.html
machines/templates/trainings/show_next_trainings.html

370 page formation ajouter bouton deja inscrit

---

frontend/src/styles/type.scss

311-shift-down-typo-highlight-marks

---

accounts/cms_plugins.py
accounts/templates/accounts/superuser-list.html

518-fix-teams

---

fabcal/tasks.py
fabcal/templates/fabcal/email/openingslot_auto_delete.html

525-implémentation-de-la-tache-ouverture-sur-réservation-ne-fonctionne-pas

---

machines/admin.py

527-ajouter-le-modèle-trainingnotification-dans-admin

---

Dockerfile

535-réservation-machine-message-de-confirmation-ne-fonctionne-pas

---

fabcal/templates/fabcal/machineslot_list.html

fix issue 545

---

frontend/src/styles/custom.scss

569-font-ne-charge-pas-sur-mobile

---

interlab/settings.py
requirements.txt

563-migration-from-djangocms-bootstrap4-to-django-cms-frontend

---

interlab/templates/navbar-header.html
locale/fr/LC_MESSAGES/django.po

add prices in navbar

---

machines/views.py

539-lors-de-la-validation-des-formations-les-autres-validations-sont-supprimées

---

fabcal/views.py

594-supprimer-une-réservation-ne-fonctionne-pas

---

fabcal/forms.py

608-mettre-en-cci-les-mail-pour-les-notifications-des-formations

---

fabcal/forms.py
fabcal/templates/fabcal/email/training_create_alert.html
fabcal/templates/fabcal/email/training_update_alert.html
fabcal/views.py
locale/fr/LC_MESSAGES/django.po

609-contrôler-les-liens-dans-les-mails

---

fabcal/cms_plugins.py
fabcal/templates/fabcal/event_card.html
fabcal/templates/fabcal/events_list.html

604-inverser-lordre-des-événements-passés

---

interlab/settings.py
interlab/templates/base.html
requirements.txt

575-mise-à-jour-du-footer

---

fabcal/admin.py

621-ajout-de-filtre-pour-créneau-machine
